"use client";
import { useAppDispatch, useAppSelector } from "@/store";
import {
  addOne,
  initCounterState,
  substractOne,
} from "@/store/counter/counterSlice";

// Generated by https://quicktype.io
export interface CounterResponse {
  method: string;
  count: number;
}

import { useEffect } from "react";

interface Props {
  value?: number;
}

const getApiCounter = async (): Promise<CounterResponse> => {
  const data = await fetch(`/api/counter`).then((res) => res.json());
  return data;
};

export const CartCounter = ({ value = 0 }: Props) => {
  const count = useAppSelector((state) => state.counter.count);
  const dispath = useAppDispatch();
  // const [count, setCount] = useState(value);

  /*   useEffect(() => {
    dispath(initCounterState(value));
  }, [dispath, value]); */

  useEffect(() => {
    getApiCounter().then(({ count }) => dispath(initCounterState(count)));
  }, [dispath, value]);

  return (
    <>
      <span className="text-9xl">{count}</span>

      <div className="flex ">
        <button
          onClick={() => dispath(addOne())}
          className="w-[100px] flex items-center justify-center p-2 mr-2 rounded-xl bg-gray-900 text-white hover:bg-gray-600 transition-all"
        >
          +1
        </button>
        <button
          onClick={() => dispath(substractOne())}
          className="w-[100px] flex items-center justify-center p-2 mr-2 rounded-xl bg-gray-900 text-white hover:bg-gray-600 transition-all"
        >
          -1
        </button>
      </div>
    </>
  );
};
